from functools import cache
from aoc_lube import fetch
import sys

sys.setrecursionlimit(2**16-1)

s = fetch(2015, 25)
row = 2947
col = 3029

def code(val, depth):
    """
    The voice on the other end of the phone continues with how the codes are actually generated.
    The first code is 20151125. After that, each code is generated by taking the previous one, multiplying it by 252533,
     and then keeping the remainder from dividing that value by 33554393.
    """
    for i in range(1, depth):
        val = val * 252533 % 33554393
    return val

@cache
def tot_diag(n):
    pos = 0
    for i in range(2, n+1):
        pos += i-1
    pos += 1
    return pos

def pos(row, col):
    return tot_diag(row + (col-1)) + (col-1)

assert pos(1, 1) == 1
assert pos(5, 1) == 11
assert pos(3, 4) == 19

d = pos(row, col)
print(f"d: {d}")
print(code(20151125, d))